export const WIDGET_OVERLAY_PREVIEW_MS = 2000;
export const WIDGET_OVERLAY_DELTA_LEAD_IN_MS = 1000;
export const WIDGET_OVERLAY_COUNTER_DURATION_MS = 1400;
export const WIDGET_OVERLAY_ZERO_HOLD_MS = 1000;
export const WIDGET_OVERLAY_HIDE_AFTER_ANIMATION_MS =
  WIDGET_OVERLAY_PREVIEW_MS
  + WIDGET_OVERLAY_DELTA_LEAD_IN_MS
  + WIDGET_OVERLAY_COUNTER_DURATION_MS
  + WIDGET_OVERLAY_ZERO_HOLD_MS;

export const OVERLAY_TEST_PAUSE_MS = 3000;
